### ISSUE TITLE
Backlight not read any longer: ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by Acer54** [atareao/backlight-indicator#3]
Hi, 
since an unknown time (maybe a few days?) I have noticed, that my backlight is not adjusted any longer (also the active-LED from my webcam stays dark).
Starting backlight-Indicator from the terminal gives the following Error-Message:

```
matthias@matthias-tuxedo:/opt/extras.ubuntu.com/backlight-indicator/bin$ ./backlight-indicator 
[Errno 2] No translation file found for domain: 'backlight-indicator'

(backlight-indicator:27195): Gtk-WARNING **: Can't set a parent on widget which has a parent

1
1
2

(backlight-indicator:27195): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
=== captured backlight: 70 ===
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/extras.ubuntu.com/backlight-indicator/share/backlight-indicator/backlightindicator.py", line 363, in get_backlight_from_webcam
    backlight = self.webcam.get_backlight()
  File "/opt/extras.ubuntu.com/backlight-indicator/share/backlight-indicator/webcam.py", line 38, in get_backlight
    self.video.create_buffers(1)
ValueError: I/O operation on closed file

```
Any idea whats may be wrong?

Regards, Matthias

**Comment by atareao** [comment]
Fixed
